/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as JogarGameIdRouteImport } from './routes/jogar.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarGameIdRoute = JogarGameIdRouteImport.update({
  id: '/jogar/$gameId',
  path: '/jogar/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/jogos': typeof JogosRoute
  '/upload': typeof UploadRoute
  '/jogar/$gameId': typeof JogarGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/jogos': typeof JogosRoute
  '/upload': typeof UploadRoute
  '/jogar/$gameId': typeof JogarGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/jogos': typeof JogosRoute
  '/upload': typeof UploadRoute
  '/jogar/$gameId': typeof JogarGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracoes' | '/jogos' | '/upload' | '/jogar/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes' | '/jogos' | '/upload' | '/jogar/$gameId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/jogos'
    | '/upload'
    | '/jogar/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  JogosRoute: typeof JogosRoute
  UploadRoute: typeof UploadRoute
  JogarGameIdRoute: typeof JogarGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar/$gameId': {
      id: '/jogar/$gameId'
      path: '/jogar/$gameId'
      fullPath: '/jogar/$gameId'
      preLoaderRoute: typeof JogarGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  JogosRoute: JogosRoute,
  UploadRoute: UploadRoute,
  JogarGameIdRoute: JogarGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
